"""Generate self-contained shareable HTML trace snapshots.

`agentlog snapshot <trace_id>` produces a single HTML file embedding both
trace data and a small renderer — no server, no external assets, no JS
build step. The file is portable: email it, drop it in a PR, attach to
a bug report.
"""
from __future__ import annotations

import html
import json
from typing import Any

from agentlog import cost as cost_mod
from agentlog import storage

_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>agentlog snapshot — {title}</title>
<style>
:root {{ --bg:#0f1115; --panel:#181b22; --panel2:#1f232c; --fg:#e6e8ee; --muted:#8a92a3; --accent:#6ea8fe; --ok:#3a9b3a; --err:#d44a4a; --warn:#c79a2a; --border:#2a2f3a; }}
*{{box-sizing:border-box;}}
html,body{{margin:0;background:var(--bg);color:var(--fg);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;font-size:14px;line-height:1.45;}}
header{{padding:14px 22px;border-bottom:1px solid var(--border);background:var(--panel);}}
header h1{{font-size:17px;margin:0;font-weight:600;}}
main{{max-width:1080px;margin:0 auto;padding:24px 22px 64px;}}
.muted{{color:var(--muted);}}
.small{{font-size:12px;}}
.row{{display:flex;gap:12px;align-items:center;flex-wrap:wrap;}}
.badge{{display:inline-block;padding:2px 9px;border-radius:10px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.5px;}}
.badge.ok{{background:rgba(58,155,58,.18);color:#6fd16f;}}
.badge.error{{background:rgba(212,74,74,.2);color:#ff7d7d;}}
.tag-chip{{display:inline-block;background:var(--panel2);border:1px solid var(--border);border-radius:10px;padding:1px 8px;font-size:11px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;margin-right:4px;color:var(--muted);}}
.tl-row{{display:grid;grid-template-columns:240px 1fr 80px;gap:12px;align-items:center;margin-bottom:4px;}}
.tl-label{{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}}
.tl-bar-wrap{{background:var(--panel);border-radius:3px;height:14px;position:relative;}}
.tl-bar{{position:absolute;top:0;bottom:0;background:var(--accent);border-radius:3px;min-width:2px;}}
.tl-bar.error{{background:var(--err);}}
.span-card{{background:var(--panel);border:1px solid var(--border);border-radius:8px;padding:8px 12px;margin-bottom:6px;}}
.span-card.error{{border-color:rgba(212,74,74,.45);}}
.span-card summary{{cursor:pointer;display:flex;gap:10px;align-items:center;}}
.span-card .kind{{font-size:11px;color:var(--muted);background:var(--panel2);padding:1px 6px;border-radius:4px;}}
.io{{display:grid;gap:10px;margin-top:8px;}}
.io h4{{margin:6px 0 3px;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.4px;}}
pre{{background:var(--panel2);padding:10px 12px;border-radius:6px;font-size:12px;margin:0;border:1px solid var(--border);white-space:pre-wrap;word-wrap:break-word;max-height:300px;overflow-y:auto;}}
.err{{color:var(--err);}}
footer{{margin-top:32px;color:var(--muted);font-size:12px;text-align:center;}}
footer a{{color:var(--accent);text-decoration:none;}}
</style>
</head>
<body>
<header>
  <h1>agentlog snapshot · <span class="muted">{title}</span></h1>
  <div class="muted small" style="margin-top:4px;">{meta}</div>
</header>
<main>
  <section>
    <h3 style="margin-top:0;">Tags & metrics</h3>
    <div class="row" id="tags">{tags_html}</div>
    <div class="row" id="metrics">{metrics_html}</div>
  </section>
  <section>
    <h3>Timeline</h3>
    <div id="timeline">{timeline_html}</div>
  </section>
  <section>
    <h3>Spans ({n_spans})</h3>
    <div id="spans">{spans_html}</div>
  </section>
</main>
<footer>generated by <a href="https://github.com/harrywinter06/agentlog">agentlog</a></footer>
</body>
</html>"""


def _esc(s: Any) -> str:
    return html.escape("" if s is None else str(s), quote=False)


def _fmt_pre(obj: Any) -> str:
    if obj is None:
        return ""
    try:
        return _esc(json.dumps(obj, indent=2, default=str))
    except (TypeError, ValueError):
        return _esc(repr(obj))


def render(trace_id: str) -> str:
    """Build the self-contained HTML string for a trace."""
    with storage.connect() as conn:
        trace = conn.execute("SELECT * FROM traces WHERE id = ?", (trace_id,)).fetchone()
        if trace is None:
            raise KeyError(f"trace not found: {trace_id}")
        spans = conn.execute(
            "SELECT * FROM spans WHERE trace_id = ? ORDER BY started_at",
            (trace_id,),
        ).fetchall()
        tags = dict(conn.execute(
            "SELECT key, value FROM trace_tags WHERE trace_id = ?", (trace_id,)
        ).fetchall())
        metrics = dict(conn.execute(
            "SELECT name, value FROM trace_metrics WHERE trace_id = ?", (trace_id,)
        ).fetchall())

    title = _esc(trace["name"])
    duration_ms = (
        round((trace["ended_at"] - trace["started_at"]) * 1000, 1)
        if trace["ended_at"] else None
    )
    cost = trace["cost_usd"] if "cost_usd" in trace.keys() else None
    meta_bits = [
        f'<span class="badge {trace["status"]}">{trace["status"]}</span>',
        f'{duration_ms} ms' if duration_ms is not None else 'in-flight',
        f'{len(spans)} spans',
    ]
    if cost is not None:
        meta_bits.append(f'${cost:.4f}')
    if trace["error_type"]:
        meta_bits.append(f'<span class="err">{_esc(trace["error_type"])}: {_esc(trace["error_message"] or "")}</span>')
    meta = " · ".join(meta_bits)

    tags_html = " ".join(f'<span class="tag-chip">{_esc(k)}={_esc(v)}</span>' for k, v in tags.items()) or '<span class="muted small">no tags</span>'
    metrics_html = " ".join(f'<span class="tag-chip">{_esc(k)}={v:.3f}</span>' for k, v in metrics.items()) or ""

    t0 = trace["started_at"]
    t1 = trace["ended_at"] or (max((s["ended_at"] or s["started_at"]) for s in spans) if spans else t0)
    total = max(t1 - t0, 0.001)
    timeline_html = ""
    for s in spans:
        start_pct = (s["started_at"] - t0) / total * 100
        end_pct = ((s["ended_at"] or t1) - t0) / total * 100
        width = max(end_pct - start_pct, 0.5)
        s_dur = round((s["ended_at"] - s["started_at"]) * 1000, 1) if s["ended_at"] else None
        timeline_html += f'''
        <div class="tl-row">
          <div class="tl-label">{_esc(s["name"])} <span class="muted small">[{_esc(s["kind"])}]</span></div>
          <div class="tl-bar-wrap"><div class="tl-bar {s["status"]}" style="left:{start_pct:.2f}%;width:{width:.2f}%"></div></div>
          <div class="muted small" style="text-align:right;">{s_dur if s_dur is not None else "—"} ms</div>
        </div>'''

    spans_html = ""
    for s in spans:
        attrs = json.loads(s["attrs_json"]) if s["attrs_json"] else None
        # If we have a cached cost on this span, surface it.
        s_cost = s["cost_usd"] if "cost_usd" in s.keys() else None
        if s_cost is None and attrs:
            s_cost = cost_mod.estimate_span_cost(attrs)
        cost_chip = f' <span class="tag-chip">${s_cost:.5f}</span>' if s_cost is not None else ""
        inp = json.loads(s["input_json"]) if s["input_json"] else None
        out = json.loads(s["output_json"]) if s["output_json"] else None
        spans_html += f'''
        <details class="span-card {s["status"]}" {"open" if s["status"] == "error" else ""}>
          <summary>
            <span class="kind">{_esc(s["kind"])}</span>
            <span style="font-weight:500;">{_esc(s["name"])}</span>
            <span class="muted small">{round((s["ended_at"] - s["started_at"])*1000, 1) if s["ended_at"] else "—"} ms</span>
            <span class="badge {s["status"]}">{s["status"]}</span>
            {cost_chip}
          </summary>
          {f'<div class="err"><b>{_esc(s["error_type"])}:</b> {_esc(s["error_message"] or "")}</div>' if s["error_type"] else ""}
          <div class="io">
            {f"<div><h4>Input</h4><pre>{_fmt_pre(inp)}</pre></div>" if inp else ""}
            {f"<div><h4>Output</h4><pre>{_fmt_pre(out)}</pre></div>" if out else ""}
            {f"<div><h4>Attrs</h4><pre>{_fmt_pre(attrs)}</pre></div>" if attrs else ""}
          </div>
        </details>'''

    return _TEMPLATE.format(
        title=title,
        meta=meta,
        tags_html=tags_html,
        metrics_html=metrics_html,
        timeline_html=timeline_html,
        n_spans=len(spans),
        spans_html=spans_html,
    )
